# build
FROM node:18-alpine as build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# deploy with nginx
FROM nginx:stable-alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
